name: buildx

on:
  workflow_dispatch:
    inputs:
     version:
        description: 'Target image to deploy to Docker Hub' 
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push urlscan-py
        uses: docker/build-push-action@v2
        with:
          context: docker
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/urlscan-py:latest,heywoodlh/urlscan-py:${{ github.event.inputs.version }}

